services:
  - type: web
    name: LlamSearch-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 4 --log-level debug
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.9.12
    healthCheckPath: /health